namespace MTWC
{
    public enum ColType
    {
        UnitId = 0,
        UnitType = 1,
        ProductionCost = 2,
        SupportCost = 3,
        ProductionTime = 4,
        HonourHandicap = 5,
        UnitBaseStrength = 6,
        UnitSize = 7,
        HonourStepValue = 8,
        GeneralCandidate,
        RebellingTroopMixes,
        RulerIDTroopAdvantage,
        RegionIDtroopAdvantage,
        DojoAdvantageModifier,
        UnitchoicesAI,
        UnitSpecialityExtraBuildinginfluences,
        BuildingsNeeded = 16,
        UnitClass = 17,
        MoralBonus = 18,
        AplicablePeriods,
        IsBaseUnitSizeScaleable,
        GeneralStats = 21,
        IsStealth,
        UnitSpecialities,
        TooltipLabels,
        Mounttype,
        ModelType,
        FactionLeaderDetails,
        FactionAssociation,
        Region,
        UnitFormationSuitability,
        UnitTaskSuitability,
        CulturesBelongingTo,
        ShipStats,
        MeleeSupportingRanks = 34,
        Impetuousness,
        FormationSpacing,
        ShieldType = 37,
        MeleesWithShield = 38,
        ShieldModifier = 39,
        IsArmourPiercing = 40,
        CavAttackBonus = 41,
        CavDefenceBonus = 42,
        FearedUnits,
        ZealImpact,
        FaithImpact,
        DismountInfo,
        DismountsInBattle,
        Weapontype = 48,
        MercenaryUnit,
        Periodassociationfornoncampaigngames,
        Factionassociationfornoncampaigngames,
        Unknown,
        HEIGHT,
        RADIUS,
        SCALE,
        PROJECTILE_TYPE,
        SAMURAI,
        MARCH_SPEED,
        RUN_SPEED,
        CHARGE_SPEED,
        MIN_TURNSPEED,
        MAX_TURNSPEED,
        TURN_TO_MOTION_SPEED,
        MAX_INMOTION_TURN,
        FORMATION_WIDTH_SPACING,
        FORMATION_LENGTH_SPACING,
        ENGAGEMENT_THRESHOLD,
        CHARGE_BONUS,
        MELEE_BONUS,
        DEFENCE_BONUS,
        ARMOUR_LEVEL,
        HONOUR_LEVEL,
        AMMO,
        FORMATIONS_PREFERRED_NUM_ROWS
    }
}
